### ISSUE TITLE
[Bug] KoalaClient-2.1.0-win-x64.exe gives a gray blank window

### ISSUE THREAD

**Issue by imesha10** [jackschedel/gpt.koaladev.io#116]
Launching KoalaClient v2.1.0b on windows gives a grey blank window. I have uninstalled and installed it just to make sure.

![image](https://github.com/jackschedel/KoalaClient/assets/16441743/8b0b1eef-b809-4132-937b-697057890c3e)

System Information:
Windows 11

**Comment by jackschedel** [comment]
Hi, could you provide your error logs? Toggle Developer Tools -> Console

**Comment by imesha10** [comment]
> Hi, could you provide your error logs? Toggle Developer Tools -> Console

I did ctrl shift I then in console I see these

```
index-a4e37498.js:8 TypeError: Cannot read properties of undefined (reading 'model')
    at Qrt (index-a4e37498.js:1653:32719)
    at Yx (index-a4e37498.js:6:19551)
    at zM (index-a4e37498.js:8:44101)
    at RM (index-a4e37498.js:8:39819)
    at uie (index-a4e37498.js:8:39745)
    at Ey (index-a4e37498.js:8:39596)
    at m7 (index-a4e37498.js:8:35959)
    at LM (index-a4e37498.js:8:34906)
    at R (index-a4e37498.js:1:11631)
    at MessagePort.F (index-a4e37498.js:1:11995)
e7 @ index-a4e37498.js:8
index-a4e37498.js:8 Uncaught TypeError: Cannot read properties of undefined (reading 'model')
    at Qrt (index-a4e37498.js:1653:32719)
    at Yx (index-a4e37498.js:6:19551)
    at zM (index-a4e37498.js:8:44101)
    at RM (index-a4e37498.js:8:39819)
    at uie (index-a4e37498.js:8:39745)
    at Ey (index-a4e37498.js:8:39596)
    at m7 (index-a4e37498.js:8:35959)
    at LM (index-a4e37498.js:8:34906)
    at R (index-a4e37498.js:1:11631)
    at MessagePort.F (index-a4e37498.js:1:11995)
```

**Comment by imesha10** [comment]
Something to mention is that last the previous version I had was compiled by cloning the repo and running the workflow for release.
However before installing this I uninstalled this and reinstalled just in case to check and it still failed.
Maybe it's the place where the chat saves and the api info is saved is the problem.
If you can tell me the location they are saved I can try deleting them if they are saved on the computer.

**Comment by jackschedel** [comment]
It is definitely a migration issue, but I would rather fix it that have you delete your history xD

**Comment by jackschedel** [comment]
For future reference, the local files are located:
On macOS: ~/Library/Application Support/koala-client
On Windows: C:\Users\<YourUsername>\AppData\Roaming\koala-client
On Linux: ~/.config/koala-client

**Comment by jackschedel** [comment]
I was able to recreate **a** (not necessarily yours) `Cannot read properties of undefined (reading 'model')` error that will be fixed in 2.1.0c, so don't reset your data yet.

I also added sourcemap building, so the error message should tell me where it is occurring in the source code now.

**Comment by jackschedel** [comment]
@imesha10 did 2.1.0c fix it?

**Comment by imesha10** [comment]
> @imesha10 did 2.1.0c fix it?

No it still does not work though different error. I'll just temporarily rename the folder for the saved chats and it works.
```
index-ef3a6568.js:8 TypeError: Cannot read properties of undefined (reading 'prompt_cost_1000')
    at mermaid-ae477ddf.js:15312:69
    at Object.useMemo (index-ef3a6568.js:6:25886)
    at wn.useMemo (index-ef3a6568.js:1:8991)
    at mermaid-ae477ddf.js:15312:69
    at Yx (index-ef3a6568.js:6:19551)
    at t7 (index-ef3a6568.js:8:3143)
    at lM (index-ef3a6568.js:8:2355)
    at sM (index-ef3a6568.js:8:1897)
    at zM (index-ef3a6568.js:8:47395)
    at RM (index-ef3a6568.js:8:39819)
e7 @ index-ef3a6568.js:8
index-ef3a6568.js:8 Uncaught TypeError: Cannot read properties of undefined (reading 'prompt_cost_1000')
    at mermaid-ae477ddf.js:15312:69
    at Object.useMemo (index-ef3a6568.js:6:25886)
    at wn.useMemo (index-ef3a6568.js:1:8991)
    at mermaid-ae477ddf.js:15312:69
    at Yx (index-ef3a6568.js:6:19551)
    at t7 (index-ef3a6568.js:8:3143)
    at lM (index-ef3a6568.js:8:2355)
    at sM (index-ef3a6568.js:8:1897)
    at zM (index-ef3a6568.js:8:47395)
    at RM (index-ef3a6568.js:8:39819)
```

**Comment by jackschedel** [comment]
This should be fixed in 2.1.0d, but there's probably going to be alot more edge cases that occur since it looks like somehow your modelDefs or atleast modelDefs[0] is null (should've been populated as default config so idk)

**Comment by jackschedel** [comment]
Adding a scuffed modelDef reset if null check on app init, ig this is what I get for not following BetterChatGPT's migration schema.

**Comment by imesha10** [comment]
> Adding a scuffed modelDef reset if null check on app init, ig this is what I get for not following BetterChatGPT's migration schema.

Ok there is no rush if this is an edge case, I'll just wait till it's released and if it doesn't fix it I'll just delete my old chats. There is nothing I need to really keep there anyways.

**Comment by jackschedel** [comment]
is it still doing it on 2.1.0d?

**Comment by imesha10** [comment]
> is it still doing it on 2.1.0d?

was just about to install it but this happened
![image](https://github.com/jackschedel/KoalaClient/assets/16441743/8ee39a9e-e116-4e76-be26-992d0457f8dc)
On Microsoft Defender:
![image](https://github.com/jackschedel/KoalaClient/assets/16441743/79066c44-d457-4217-b732-6c8580888df6)
On virus total it's clean
https://www.virustotal.com/gui/file/eb47eda7781cfa622c446fbd1e493ab87fa14bbd98ce3f75fb58bb87564d8c49?nocache=1

However the file is quarentied.

**Comment by imesha10** [comment]
I'll build this by myself and see if it happens again.

**Comment by imesha10** [comment]
I built it.

(I forked the repo, then ran the workflow to build and publish desktop app and this time didn't qurentine the file)

However the error remains:
```
index-84599a02.js:8 TypeError: Cannot read properties of undefined (reading 'name')
    at mermaid-ae477ddf.js:15312:69
    at yy (index-84599a02.js:8:24296)
    at d1 (index-84599a02.js:8:42448)
    at IM (index-84599a02.js:8:36651)
    at bu (index-84599a02.js:6:3288)
    at hie (index-84599a02.js:8:41325)
    at Sh (index-84599a02.js:8:40309)
    at LM (index-84599a02.js:8:35758)
    at R (index-84599a02.js:1:11631)
    at MessagePort.F (index-84599a02.js:1:11995)
e7 @ index-84599a02.js:8
index-84599a02.js:6 Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at mermaid-ae477ddf.js:15312:69
    at yy (index-84599a02.js:8:24296)
    at d1 (index-84599a02.js:8:42448)
    at IM (index-84599a02.js:8:36651)
    at bu (index-84599a02.js:6:3288)
    at hie (index-84599a02.js:8:41325)
    at Sh (index-84599a02.js:8:40309)
    at LM (index-84599a02.js:8:35758)
    at R (index-84599a02.js:1:11631)
    at MessagePort.F (index-84599a02.js:1:11995)
```

**Comment by imesha10** [comment]
I think at this point if this is just an edge case and it's just my saves that are corrupted then I'm fine with deleting them. (it works after deleting the old saves entire folder)

As I mentioned before I built your app by forking it before to test out the new api menu when it wasn't done yet so it might have corrupted the saves there. I don't know but it might be just a case of me only.

Please close this issue if you also agree that this is probably just an edge case other probably won't get.

**Comment by jackschedel** [comment]
Weird about the virus check; this is why I provide the build hash data.

2.1.0e will have another fix, can't guarantee it'll be the last tho 🥲
